#!/bin/bash
COWPATH=${COWPATH:-/usr/share/cowsay/cows}
COWSAY=/usr/games/cowsay
COWTHINK=/usr/games/cowthink
FORTUNE=/usr/games/fortune

# read blacklist from home or etc
BLACKLIST=""
if [ -s $HOME/.cowfortune/blacklist ]; then
	BLACKLIST=$(cat $HOME/.cowfortune/blacklist)
elif [ -s /etc/cowfortune/blacklist ]; then
	BLACKLIST=$(cat /etc/cowfortune/blacklist)
fi

# read whitelist from home or etc
WHITELIST=""
if [ -s $HOME/.cowfortune/whitelist ]; then
	WHITELIST=$(cat $HOME/.cowfortune/whitelist)
elif [ -s /etc/cowfortune/whitelist ]; then
	WHITELIST=$(cat /etc/cowfortune/whitelist)
fi

# get all existing cows
COWS=$(ls --format="single-column" ${COWPATH}|sed 's/\.cow//g')

# maybe filter from whitelist so we only have existing cows
if [ -n "$WHITELIST" ]; then
	WHITELIST=$(echo $WHITELIST|tr ' ' '|')
	COWS=$(echo "$COWS"|grep -E $WHITELIST)
fi

# filter the blacklist from the remaining cows
if [ -n "$BLACKLIST" ]; then
	BLACKLIST=$(echo $BLACKLIST|tr ' ' '|')
	COWS=$(echo "$COWS"|grep -v -E $BLACKLIST)
fi
COWS=${COWS}|tr "\n" " "

set -- "$COWS"
declare -a COWS=($*)
RANGE=${#COWS[@]}
NUMBER=$RANDOM
let "NUMBER %= $RANGE"
COW=${COWS[$NUMBER]}
RANGE=2
number=$RANDOM
let "number %= $RANGE"
case $number in
0)
    command=$COWSAY
    ;;
1)
    command=$COWTHINK
    ;;
esac
$FORTUNE -s | $command -f $COW
